sudo: false
language: java
cache:
  directories:
  - $HOME/.gradle
before_script: git checkout $TRAVIS_BRANCH
script: ./gradlew clean release cobertura --info --stacktrace
jdk: oraclejdk7
env: TERM=dumb
after_success: ./gradlew coveralls
addons:
  apt:
    packages:
    - git
