language: java
script: ./gradlew clean build
jdk: oraclejdk7
env: TERM=dumb
# after_success: ./gradlew jacocoRootReport coveralls
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y git
