sudo: false
addons:
  apt:
    packages:
    - git
language: groovy
jdk: oraclejdk7
env: TERM=dumb
cache:
  directories:
  - $HOME/.gradle
before_install:
  - git config user.email "tobias.schulte@gliderpilot.de"
  - git config user.name "Travis-CI"
  - git config url.https://.insteadOf git://
  - git checkout -qf $TRAVIS_BRANCH
# skip default gradlew assemble
install:
  - echo "skip default gradlew assemble"
script:
  - ./gradlew release cobertura -Dorg.ajoberstar.grgit.auth.username=${GH_TOKEN} -Dorg.ajoberstar.grgit.auth.password -Dgradle.publish.key=${GRADLE_KEY} -Dgradle.publish.secret=${GRADLE_SECRET} --info --stacktrace
after_success:
  - ./gradlew coveralls
